apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drone-swarm
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.template.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

